version: 2
models: []
sources: []
seeds:
  - name: raw_customers
    columns:
      - name: id
        data_type: INTEGER
      - name: first_name
        data_type: VARCHAR
      - name: last_name
        data_type: VARCHAR
  - name: raw_orders
    columns:
      - name: id
        data_type: INTEGER
      - name: user_id
        data_type: INTEGER
      - name: order_date
        data_type: DATE
      - name: status
        description: '{{ doc("orders_status") }}'
  - name: raw_payments
    columns:
      - name: id
        data_type: INTEGER
      - name: order_id
        data_type: INTEGER
      - name: payment_method
        data_type: VARCHAR
      - name: amount
        data_type: INTEGER
