[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dbt-osmosis"
version = "0.14.0"
description = "A dbt utility for managing YAML to make developing with dbt more delightful."
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [{ name = "z3z1ma", email = "butler.alex2010@gmail.com" }]
keywords = ["dbt", "yaml", "osmosis"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.9,<3.13"

dependencies = [
  "click>7",
  "dbt-core>=1.8,<1.10",
  "ruamel.yaml>=0.17",
  "rich>=10",
  "pluggy>=1.5.0",
]

[project.optional-dependencies]
duckdb = ["dbt-duckdb>=1.0.0"]
sqlite = ["dbt-sqlite>=1.0.0"]
postgres = ["dbt-postgres>=1.0.0"]
workbench = [
  "streamlit>=1.20.0",
  "streamlit-ace>=0.1.0",
  "ydata-profiling>=3.6.0",
  "feedparser~=6.0.10",
  "streamlit-elements-fluence>=0.1.4",
]

openai = ["openai>0.28.0"]

dev = [
  "black>=21.9b0",
  "mypy>=0.910",
  "pylint>=2.11.1",
  "pytest~=7.4.2",
  "pre-commit>3.0.0",
]

[project.scripts]
"dbt-osmosis" = "dbt_osmosis.main:cli"

[tool.black]
line-length = 100
target-version = ["py39", "py310", "py311"]
preview = true

[tool.isort]
color_output = true
line_length = 100
profile = "black"
src_paths = ["src"]
include_trailing_comma = true

[tool.ruff]
line-length = 100
