version: 2
models:
  - name: customers
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null

      - name: first_name
        description: Customer's first name. PII.

      - name: last_name
        description: Customer's last name. PII.

      - name: first_order
        description: Date (UTC) of a customer's first order

      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order

      - name: number_of_orders
        description: Count of the number of orders a customer has placed

      - name: customer_lifetime_value
        data_type: DOUBLE
        description: ''

      - name: customer_average_value
        description: ''
        data_type: DECIMAL(18,3)
  - name: orders
    description: This table has basic information about orders, as well as some derived facts based on payments

    columns:
      - name: order_id
        tests:
          - unique
          - not_null
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

        description: '{{ doc("orders_status") }}'
      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card
        tests:
          - not_null

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon
        tests:
          - not_null

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer
        tests:
          - not_null

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card
        tests:
          - not_null
      - name: amount
        description: Total amount (AUD) of the order
        tests:
          - not_null
  - name: orders_prefix
    columns:
      - name: o_order_id
        description: ''
        data_type: INTEGER
      - name: o_customer_id
        description: ''
        data_type: INTEGER
      - name: o_order_date
        description: ''
        data_type: DATE
      - name: o_status
        description: '{{ doc("orders_status") }}'
        data_type: VARCHAR
      - name: o_credit_card_amount
        description: ''
        data_type: DOUBLE
      - name: o_coupon_amount
        description: ''
        data_type: DOUBLE
      - name: o_bank_transfer_amount
        description: ''
        data_type: DOUBLE
      - name: o_gift_card_amount
        description: ''
        data_type: DOUBLE
      - name: o_amount
        description: ''
        data_type: DOUBLE
